# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UserLoginGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UserLogin(object):
    def setupUi(self, UserLogin):
        UserLogin.setObjectName("UserLogin")
        UserLogin.resize(450, 550)
        UserLogin.setMinimumSize(QtCore.QSize(450, 550))
        UserLogin.setMaximumSize(QtCore.QSize(450, 550))
        UserLogin.setStyleSheet("#centralwidget, #UserLogin{\n"
"    background-color: rgb(28,37,65);\n"
"}\n"
"QLineEdit {\n"
"    padding-left: 5px;\n"
"    color: hsl(281, 50%, 68%);\n"
"    background-color: transparent;\n"
"    border-bottom: 2px hsl(281, 50%, 68%);\n"
"    border-style: solid;\n"
"}\n"
"QLineEdit:focus{\n"
"    border-bottom-color: hsl(281, 50%,30%);\n"
"}\n"
"QPushButton{\n"
"    all: unset;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    background-color: hsl(281, 50%, 68%);\n"
"    color: rgb(28,37,65);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: hsl(281, 50%,30%);\n"
"    color: hsl(281, 50%, 85%);\n"
"}\n"
"#register_question{\n"
"    color: white;\n"
"}\n"
"#register_button{\n"
"    color: hsl(281, 50%, 68%);\n"
"    background-color: transparent;\n"
"}\n"
"#register_button:hover{\n"
"    color: hsl(281, 50%, 30%);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(UserLogin)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.verticalLayout.addItem(spacerItem)
        self.user_firstname_frame = QtWidgets.QFrame(self.centralwidget)
        self.user_firstname_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.user_firstname_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.user_firstname_frame.setObjectName("user_firstname_frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.user_firstname_frame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.user_firstname = QtWidgets.QLineEdit(self.user_firstname_frame)
        self.user_firstname.setMinimumSize(QtCore.QSize(0, 40))
        self.user_firstname.setMaximumSize(QtCore.QSize(270, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.user_firstname.setFont(font)
        self.user_firstname.setText("")
        self.user_firstname.setFrame(False)
        self.user_firstname.setObjectName("user_firstname")
        self.horizontalLayout_3.addWidget(self.user_firstname)
        self.verticalLayout.addWidget(self.user_firstname_frame)
        spacerItem1 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem1)
        self.user_lastname_frame = QtWidgets.QFrame(self.centralwidget)
        self.user_lastname_frame.setMinimumSize(QtCore.QSize(0, 0))
        self.user_lastname_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.user_lastname_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.user_lastname_frame.setObjectName("user_lastname_frame")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.user_lastname_frame)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.user_lastname = QtWidgets.QLineEdit(self.user_lastname_frame)
        self.user_lastname.setMinimumSize(QtCore.QSize(0, 40))
        self.user_lastname.setMaximumSize(QtCore.QSize(270, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.user_lastname.setFont(font)
        self.user_lastname.setText("")
        self.user_lastname.setFrame(False)
        self.user_lastname.setObjectName("user_lastname")
        self.horizontalLayout_6.addWidget(self.user_lastname)
        self.verticalLayout.addWidget(self.user_lastname_frame)
        spacerItem2 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem2)
        self.user_username_frame = QtWidgets.QFrame(self.centralwidget)
        self.user_username_frame.setMinimumSize(QtCore.QSize(0, 0))
        self.user_username_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.user_username_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.user_username_frame.setObjectName("user_username_frame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.user_username_frame)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.user_username = QtWidgets.QLineEdit(self.user_username_frame)
        self.user_username.setMinimumSize(QtCore.QSize(0, 40))
        self.user_username.setMaximumSize(QtCore.QSize(270, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.user_username.setFont(font)
        self.user_username.setText("")
        self.user_username.setFrame(False)
        self.user_username.setObjectName("user_username")
        self.horizontalLayout_5.addWidget(self.user_username)
        self.verticalLayout.addWidget(self.user_username_frame)
        spacerItem3 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem3)
        self.user_password_frame = QtWidgets.QFrame(self.centralwidget)
        self.user_password_frame.setMinimumSize(QtCore.QSize(0, 0))
        self.user_password_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.user_password_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.user_password_frame.setObjectName("user_password_frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.user_password_frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.user_password = QtWidgets.QLineEdit(self.user_password_frame)
        self.user_password.setMinimumSize(QtCore.QSize(0, 40))
        self.user_password.setMaximumSize(QtCore.QSize(270, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.user_password.setFont(font)
        self.user_password.setText("")
        self.user_password.setFrame(False)
        self.user_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.user_password.setObjectName("user_password")
        self.horizontalLayout_2.addWidget(self.user_password, 0, QtCore.Qt.AlignTop)
        self.verticalLayout.addWidget(self.user_password_frame)
        self.register_frame = QtWidgets.QFrame(self.centralwidget)
        self.register_frame.setMinimumSize(QtCore.QSize(0, 50))
        self.register_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.register_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.register_frame.setObjectName("register_frame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.register_frame)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.register_question = QtWidgets.QLabel(self.register_frame)
        self.register_question.setMinimumSize(QtCore.QSize(265, 0))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.register_question.setFont(font)
        self.register_question.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.register_question.setIndent(0)
        self.register_question.setObjectName("register_question")
        self.horizontalLayout_4.addWidget(self.register_question, 0, QtCore.Qt.AlignRight)
        self.register_button = QtWidgets.QPushButton(self.register_frame)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.register_button.setFont(font)
        self.register_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.register_button.setObjectName("register_button")
        self.horizontalLayout_4.addWidget(self.register_button, 0, QtCore.Qt.AlignLeft)
        self.verticalLayout.addWidget(self.register_frame)
        spacerItem4 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem4)
        self.submit_box = QtWidgets.QFrame(self.centralwidget)
        self.submit_box.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.submit_box.setFrameShadow(QtWidgets.QFrame.Raised)
        self.submit_box.setObjectName("submit_box")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.submit_box)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.submit = QtWidgets.QPushButton(self.submit_box)
        self.submit.setMinimumSize(QtCore.QSize(0, 35))
        self.submit.setMaximumSize(QtCore.QSize(175, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.submit.setFont(font)
        self.submit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.submit.setObjectName("submit")
        self.horizontalLayout.addWidget(self.submit, 0, QtCore.Qt.AlignVCenter)
        self.verticalLayout.addWidget(self.submit_box)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.verticalLayout.addItem(spacerItem5)
        UserLogin.setCentralWidget(self.centralwidget)

        self.retranslateUi(UserLogin)
        QtCore.QMetaObject.connectSlotsByName(UserLogin)

    def retranslateUi(self, UserLogin):
        _translate = QtCore.QCoreApplication.translate
        UserLogin.setWindowTitle(_translate("UserLogin", "MainWindow"))
        self.user_firstname.setPlaceholderText(_translate("UserLogin", "Firstname"))
        self.user_lastname.setPlaceholderText(_translate("UserLogin", "Lastname"))
        self.user_username.setPlaceholderText(_translate("UserLogin", "Username"))
        self.user_password.setPlaceholderText(_translate("UserLogin", "Password"))
        self.register_question.setText(_translate("UserLogin", "Do not have an account? "))
        self.register_button.setText(_translate("UserLogin", "Register"))
        self.submit.setText(_translate("UserLogin", "Start App"))
